name: Basic Develop Test

on:
  push:
    branches:
      - main
      - develop
      - release/*

    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: |
      cbsh --script {0}

jobs:
  basic-usage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: '*'
        enable-plugins: true
    - run: |
        echo (version); echo $"(char nl)Dir contents:(char nl)"; ls ((which cbsh).path.0 | path dirname)
    - run: |
        echo $'Current env:(char nl)'
        echo $env
    - name: You can run bash commands, too
      run: pwd && ls -la
      shell: bash
