name: Basic Develop Test

on: [workflow_dispatch]

defaults:
  run:
    shell: cbsh {0}

jobs:
  basic-usage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: '*'
        enable-plugins: true
    - run: print (version); print $"(char nl)Dir contents:(char nl)"; ls ((which cbsh).path.0 | path dirname)
    - run: |
        print $'Current env:(char nl)'
        print $env
    - name: You can run bash commands, too
      run: pwd && ls -la
      shell: bash
