name: Couchbase Shell Module Test 2

on:
  push:
    branches:
      - main
      - develop
      - release/*
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: cbsh {0}

jobs:
  test-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
        ver: [0.75.2]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, cbsh@${{matrix.ver}})
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup cbsh@latest
      uses: ldoguin/setup-cbsh@develop
      with:
        enable-plugins: false
        version: ${{matrix.ver}}
    - name: Show Couchbase Shell Version and NU_LIB_DIRS
      run: |
        print $'Couchbase Shell version info:(char nl)'; print (version)
        print 'NU_LIB_DIRS:'
        $env.NU_LIB_DIRS | print
    - name: Prepare Couchbase Shell Modules
      run: |
        # Licbshx: '/home/runner/.config/cbshshell'
        # Windows: 'C:/Users/runneradmin/AppData/Roaming/cbshshell'
        # Darwin: '/Users/runner/Library/Application Support/cbshshell'
        let LIB_DIR = [$cbsh.default-config-dir 'scripts'] | path join
        if not ($LIB_DIR | path exists) { mkdir $LIB_DIR }
        cp -r cbsh/* $LIB_DIR
        print $'Contents of ($LIB_DIR):'
        ls $LIB_DIR
    - name: Use Your Couchbase Shell Modules
      run: |
        use module.cbsh *
        print (get-env 'ABC-XYZ' 'DEFAULT-ABC-XYZ')
