name: Couchbase Shell Module Test

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/cbsh-lib
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: cbsh --script {0}

jobs:
  test-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        ver: [v0.75.2]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, cbsh@${{matrix.ver}})
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup cbsh@latest
      uses: ldoguin/setup-cbsh@develop
      with:
        enable-plugins: true
        version: ${{matrix.ver}}
      env:
        ACTIONS_STEP_DEBUG: true
    - name: Show Couchbase Shell Version
      run: echo $'Couchbase Shell version info:(char nl)'; echo (version)
    - name: Use Your Couchbase Shell Modules
      run: |
        cbsh -c "use nu/module.nu *; echo (get-env 'ABC-XYZ' 'DEFAULT-ABC-XYZ')"
    - name: Use Your Couchbase Shell Modules by Absolute Path
      run: |
        use ${{ github.workspace }}/nu/module.nu *
        echo 'Use module from: ${{ github.workspace }}/nu/module.nu'
        echo (get-env 'ABC-XYZ' 'DEFAULT-ABC-XYZ-ABSOLUTE-PATH')
