name: Build Workflow and Use Couchbase Shell Nightly Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - develop
      - release/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'
    - name: Build Setup Script
      run: |
        npm i -g pnpm
        pnpm i --registry=https://registry.npmmirror.com
        pnpm run lint
        pnpm run build

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crate:
          - { owner: couchbaselabs, name: couchbase-shell }

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, ${{ matrix.crate.owner }}/${{ matrix.crate.name }})
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup ${{ matrix.crate.owner }}/${{ matrix.crate.name }}
      uses: ./
      with:
        version: nightly
        enable-plugins: true
      env:
        ACTIONS_STEP_DEBUG: true
    - name: Show Couchbase Shell Path and Related Assets
      run: which $(printf cbsh | tr '[:upper:]' '[:lower:]') && echo "Dir contents --->:" && ls -la "$(dirname `which cbsh`)"
      shell: bash
    - name: Spawn a Couchbase Shell Session and Display Version Info
      run: cbsh -c 'echo (version); echo $"(char nl)Dir contents:(char nl)"; ls ((which cbsh).path.0 | path dirname)'
      shell: bash
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#custom-shell
    - name: Use Couchbase Shell as Default Shell
      shell: cbsh --script {0}
      run: |
        echo $'Current env:(char nl)'
        echo $env
